markdown: kramdown
highlighter: rouge

production_url: '/squeak-actors'

defaults:
  -
    scope:
      path: ""
    values:
      layout: page

title: Squeak Actors

author:
  twitter: 'leastfixedpoint'
  fullname: 'Tony Garnock-Jones'
  gravatar: 'tonyg@leastfixedpoint.com'
  email: 'tonyg@leastfixedpoint.com'

links:
  squeaksource: 'http://www.squeaksource.com/Actors.html'
  github: 'https://github.com/tonyg/squeak-actors'
  documentation: 'https://tonyg.github.io/squeak-actors/'

squeak_updatenumber: 17762

contact_email: 'tonyg@leastfixedpoint.com'

copyrightyears: '2017â€“2018'

section_links:
  'User Manual': '/manual.html'
  'Tutorials': '/tutorials.html'